# ── Server ──
server.port=${PORT:4000}

# ── MySQL connection ──
spring.datasource.url=jdbc:mysql://altaria.proxy.rlwy.net:51937/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=iIdWefTOcGveophHBCuYnIuPKZdSStdL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ── JPA / Hibernate ──
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ── Seed ──
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

# ── Multipart ──
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Directory to scan for downloaded songs (optional). If empty, defaults to {user.home}/Downloads
songs.download.dir=