const MODERN_PLAYLIST = [
  { id: "m01", title: "Kesariya", artist: "Arijit Singh", duration: 264, audioUrl: "", src: "/songs/modern/01.mp3" },
  { id: "m02", title: "Raataan Lambiyan", artist: "Jubin Nautiyal, Asees Kaur", duration: 231, audioUrl: "", src: "/songs/modern/02.mp3" },
  { id: "m03", title: "Tum Hi Ho", artist: "Arijit Singh", duration: 261, audioUrl: "", src: "/songs/modern/03.mp3" },
  { id: "m04", title: "Tera Ban Jaunga", artist: "Akhil Sachdeva, Tulsi Kumar", duration: 218, audioUrl: "", src: "/songs/modern/04.mp3" },
  { id: "m05", title: "Hawayein", artist: "Arijit Singh", duration: 296, audioUrl: "", src: "/songs/modern/05.mp3" },
  { id: "m06", title: "Bekhayali", artist: "Sachet Tandon", duration: 312, audioUrl: "", src: "/songs/modern/06.mp3" },
  { id: "m07", title: "Ik Vaari Aa", artist: "Arijit Singh", duration: 278, audioUrl: "", src: "/songs/modern/07.mp3" },
  { id: "m08", title: "Channa Mereya", artist: "Arijit Singh", duration: 284, audioUrl: "", src: "/songs/modern/08.mp3" },
  { id: "m09", title: "Ae Dil Hai Mushkil", artist: "Arijit Singh", duration: 255, audioUrl: "", src: "/songs/modern/09.mp3" },
  { id: "m10", title: "Agar Tum Saath Ho", artist: "Arijit Singh, Alka Yagnik", duration: 320, audioUrl: "", src: "/songs/modern/10.mp3" },
  { id: "m11", title: "Phir Bhi Tumko Chaahunga", artist: "Arijit Singh, Shashaa Tirupati", duration: 268, audioUrl: "", src: "/songs/modern/11.mp3" },
  { id: "m12", title: "Kalank", artist: "Arijit Singh", duration: 302, audioUrl: "", src: "/songs/modern/12.mp3" },
  { id: "m13", title: "Dil Diyan Gallan", artist: "Atif Aslam", duration: 244, audioUrl: "", src: "/songs/modern/13.mp3" },
  { id: "m14", title: "Mere Naam Tu", artist: "Abhay Jodhpurkar", duration: 258, audioUrl: "", src: "/songs/modern/14.mp3" },
  { id: "m15", title: "Lut Gaye", artist: "Jubin Nautiyal", duration: 236, audioUrl: "", src: "/songs/modern/15.mp3" },
  { id: "m16", title: "Shayad", artist: "Arijit Singh", duration: 249, audioUrl: "", src: "/songs/modern/16.mp3" },
  { id: "m17", title: "Pal", artist: "Arijit Singh, Shreya Ghoshal", duration: 271, audioUrl: "", src: "/songs/modern/17.mp3" },
  { id: "m18", title: "Tujhe Kitna Chahne Lage", artist: "Arijit Singh", duration: 263, audioUrl: "", src: "/songs/modern/18.mp3" },
  { id: "m19", title: "Pehla Pyaar", artist: "Armaan Malik", duration: 228, audioUrl: "", src: "/songs/modern/19.mp3" },
  { id: "m20", title: "Teri Mitti", artist: "B Praak", duration: 289, audioUrl: "", src: "/songs/modern/20.mp3" },
  { id: "m21", title: "Judaai", artist: "Arijit Singh", duration: 245, audioUrl: "", src: "/songs/modern/21.mp3" },
  { id: "m22", title: "Kho Gaye Hum Kahan", artist: "Jasleen Royal, Prateek Kuhad", duration: 233, audioUrl: "", src: "/songs/modern/22.mp3" },
  { id: "m23", title: "Apna Bana Le", artist: "Arijit Singh", duration: 252, audioUrl: "", src: "/songs/modern/23.mp3" },
  { id: "m24", title: "Naina", artist: "Amit Trivedi", duration: 219, audioUrl: "", src: "/songs/modern/24.mp3" },
  { id: "m25", title: "Zindagi Kuch Toh Bata", artist: "Jubin Nautiyal", duration: 274, audioUrl: "", src: "/songs/modern/25.mp3" },
];

export default MODERN_PLAYLIST;
